### ISSUE TITLE
Using Standalone shaders results into hightspeed vehicles in GTA V

### ISSUE THREAD

**Issue by kineese** [luluco250/FXShaders#2]
When player use the shader it seems like it affects the GTA engine resulting that a vehicle drives faster than allowed by the game itself

**Comment by luluco250** [comment]
ReShade shaders should not affect the functionality of the game, they simply don't have that capacity, they're just effects applied of the screen.

It may be something to do with some other mods being used in the game or maybe the game behaves differently at lower framerates (which is common in GTA games) which _can_ be caused ReShade effects but is not inherently in their control.

It could also just be a bug with ReShade itself, but there's no code in the shaders in this repository that should directly cause physics bugs like you describe.
