### ISSUE TITLE
MagicHDR.fx Failed to create texture!

### ISSUE THREAD

**Issue by Veskomenas** [luluco250/FXShaders#3]
I was adjusting reshade preset in the game. At end of the editing i came to last effect **"MagicHDR.fx"** (it was working perfectly fine), than adjusted few sliders and at the end i want to see how it will look with **"Adaptive HDR"** so i changed value from **0** to **1** and now it get this error code: **"Failed to create texture V__fxshaders__bloom6tex"**. I tried to reinstall it because most of the time this method fix everythink. But for for this time it doesn't... So maybe anyone know how to fix it? Maybe generated code will help to track down the problem... [Compiled result.txt](https://github.com/luluco250/FXShaders/files/5663454/Compiled.result.txt)

**Comment by luluco250** [comment]
What game/API were you trying to use it with?
It's a bit broken in Minecraft due to limitations in its ancient OpenGL implementations.

**Comment by Veskomenas** [comment]
Game: **Elite Dangerous**, API: **Directx 11**. Thanks for your time. But i fixed my self. The issue was not the MagicHDR.fx code but the left over code in preset file. I just reverted it back at **PreprocessorDefinitions=** line where was **MAGICHDR ADAPTIVE=** **1** to **0**

**Comment by AFailingGuy** [comment]
So how do you fix OpenGL APi
